Repository CodeForAfrica/sensors.AFRICA-api, pull requests merged in 2020-12, with the labels that each got.

#75 Ft locations endpoint
  sensorsafrica/api/v2/router.py
  sensorsafrica/api/v2/serializers.py
  sensorsafrica/api/v2/views.py
Labels: enhancement

#76 Adds Node creation API endpoint
  sensorsafrica/api/v2/serializers.py
  sensorsafrica/api/v2/views.py
Labels: enhancement

#79 [Hotfix] Creation api
  Makefile
  sensorsafrica/api/v2/router.py
  sensorsafrica/api/v2/serializers.py
  sensorsafrica/api/v2/views.py
  sensorsafrica/tests/conftest.py
  sensorsafrica/tests/test_node_view.py
  sensorsafrica/tests/test_sensor_location_view.py
  sensorsafrica/tests/test_sensor_type_view.py
  sensorsafrica/tests/test_sensor_view.py
Labels: bug

#81 [Feature] Public / Private Data
  requirements.txt
  sensorsafrica/api/v2/router.py
  sensorsafrica/api/v2/views.py
  sensorsafrica/management/commands/calculate_data_statistics.py
Labels: bug, dependencies, enhancement

#82 [Fix] Default Authentication Classes
  sensorsafrica/settings.py
Labels: bug

#83 [Fix] serializer
  sensorsafrica/api/v2/serializers.py
  sensorsafrica/api/v2/views.py
Labels: bug
