Repository CodeForAfrica/sensors.AFRICA-api, pull requests merged in 2021-01, with the labels that each got.

#84 [Fix] Missing upload data timestamp
  sensorsafrica/management/commands/upload_to_ckan.py
Labels: bug

#85 [Fix] Missing upload data timestamp
  sensorsafrica/management/commands/upload_to_ckan.py
Labels: bug

#87 [Feature] Upload public data
  sensorsafrica/management/commands/upload_to_ckan.py
Labels: enhancement

#86 [Feature] Make v1/now return public data only
  sensorsafrica/api/v1/router.py
  sensorsafrica/api/v1/views.py
Labels: enhancement

#89 [Feature] /v2/nodes should include node owner
  sensorsafrica/api/v2/views.py
Labels: enhancement

#88 [Fix] v1/node should check groups
  sensorsafrica/api/v1/router.py
  sensorsafrica/api/v1/views.py
Labels: bug, enhancement

#90 Fix node owner
  sensorsafrica/api/v2/views.py
Labels: bug

#91 Adds endpoint for providing metadata
  sensorsafrica/api/v2/router.py
  sensorsafrica/api/v2/views.py
  sensorsafrica/settings.py
Labels: enhancement
